# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: chess 
spec:
  # Datastore configuration
  storeConfig:
    database: my-chess-database
    statefulStore:
      # Name of a deployed Datastore to use.
      name: my-chess-database
  containers:
    - image: sebastianharko/chess:latest
      name: chess
